### ISSUE TITLE
Invalid sha1 checksum in maven central

### ISSUE THREAD

**Issue by adamnfish** [Taig/Communicator#3]
I'm unable to resolve Communicator as a dependency in sbt due to the following warning. Are the checksums corrupt?

    problem while downloading module descriptor: http://repo1.maven.org/maven2/io/taig/communicator_2.11/2.0.2/communicator_2.11-2.0.2.pom: invalid sha1: expected=8bcb649e6bb835510a337dce76ffa340c933d26f computed=f8ed1419dd1bf3964d1143c4a376adcd75d360ee

I get the same error (with different checksums) when trying `2.0.1`. However, `2.0.0` *does* work.

**Comment by Taig** [comment]
Confirmed, looking into it!

**Comment by Taig** [comment]
Just pushed 2.1.0, and it does resolve properly. No clue why it failed for the last minors. Please note the updated documentation. Things got simplified a lot, wasn't aware anyone was using this.

````
[info] downloading https://repo1.maven.org/maven2/io/taig/communicator_2.11/2.1.0/communicator_2.11-2.1.0.jar ...
[info] 	[SUCCESSFUL ] io.taig#communicator_2.11;2.1.0!communicator_2.11.jar (743ms)
````

**Comment by adamnfish** [comment]
Thanks @Taig, I was just evaluating it as a standalone Scala HTTP client to rival e.g. Dispatch. Very much appreciate your time!
