### ISSUE TITLE
README.md File

### ISSUE THREAD

**Issue by AbimbolaE** [Taig/Communicator#5]
Hi there,

This project looks pretty cool and simple and I'm attempting to use it in my Scala / Android project.
However, the documentation seems out of date, especially the `.done` callback which expects the `Response.Payload` class to be a class class which can be pattern matched whereas, it is a simple class.

Any chance of an updated README.md?

Thanks!

**Comment by Taig** [comment]
I just fixed the flawed sample code. Let me know if it works for you.

**Comment by AbimbolaE** [comment]
Hi there,

Thanks for the super quick response, I'm currently trying the `.done` callback with the `Response` class but I can't pattern match against it if it is not a case class. I'm using version 2.2.4 of this library and the import im using is `import io.taig.communicator.{Request, _}`

**Comment by AbimbolaE** [comment]
On the other hand, the example below compiles, but I haven't gotten it working all together

    .done {
      case r: Response.Payload[String] =>Log.d("SignUp", s"Status Code: ${r.code}")
    }

**Comment by Taig** [comment]
`Response` has an `unapply` method though `def unapply[T]( response: Response with Payload[T] ) = Some( response.code, response.body )` which allows to perform pattern matching. Remove the `.Payload` part from your code (that does do longer exist).

**Comment by AbimbolaE** [comment]
Ah, thanks!

Do you have any examples of projects which use this library?? Complete examples of doing GET and POST requests. I believe it would be very useful to have a complete code snippet of each in the README.md

**Comment by Taig** [comment]
The request configuration is done with the underlying okhttp request builder. You'll find more example on their [website](http://square.github.io/okhttp/). All in all I'm not particularly happy with Communicator and don't like to promote its usage. It's messing up the flawed scala Future API even further. But I also haven't discovered a better alternative yet.

**Comment by AbimbolaE** [comment]
I think the idea of wrapping of the Java API's that work on Android such as OkHttp makes perfect sense. I would contribute to making this one much better as I know a decent amount about Scala Future API but, I have never used the OkHttp library extensively and as such, I don't feel I know it well enough to make a wrapper for it myself. Maybe in a few months, I'll look into it!

**Comment by Taig** [comment]
OkHttp underwent major changes with its recent v3 release. I didn't get around migrating yet.

**Comment by AbimbolaE** [comment]
Hey Taig,

I've made a Scala library for making HTTP requests title 'Cirrus', you can find it here:
https://github.com/Godis/Cirrus

I'm actively looking for anyone has experience with working with HTTP requests and is willing to contribute so, feel free to drop by sometime and have a look at the codebase!

Cheers!
