### ISSUE TITLE
Creating responses in tests

### ISSUE THREAD

**Issue by fsvehla** [Taig/communicator#50]
I struggle a bit on how to test code that uses Communicator, Ideally I’d create a `Task[Response.With[String]]` by hand in test and exchange it in tests, but the trait is sealed and the constructor is package private.

**Comment by Taig** [comment]
I'm happy to introduce a public constructor. Could you sketch out a bit what you are trying to achieve by an example?

**Comment by Taig** [comment]
Made `Response.apply` public in 3.2.2
