### ISSUE TITLE
How to extend types of Parsers?

### ISSUE THREAD

**Issue by fishmacs** [Taig/communicator#56]
Say, the response is a JSON which can be parsed to a student object:

`case class Student(username: String, id: Int)`

I want a Parser[Student] with parse method return a Task[Response[Student]]
How can I?

**Comment by fishmacs** [comment]
got it, Request.parse accepts an implicit parameter with type of Parser

**Comment by Taig** [comment]
Exactly, but generally I'd suggest to avoid creating such specific Parsers. Use the `Json` parser and then rely on `circe` tools to go to a `Student` from there.

```scala 
val response: Response[Json] = ???
val student: Decoder.Result[Student] = response.body.as[Student]
```

**Comment by fishmacs** [comment]
Great! Thanks

**Comment by fishmacs** [comment]
Oh, I thought I had understand, but not. 
Any hint?

**Comment by Taig** [comment]
Well, can you be a bit more specific about what exactly you didn't understand?

**Comment by fishmacs** [comment]
How to get `Resonse[Json]`? like `Response[String].map(parse(_.body))`?

and how circe know how to parse to Student?

**Comment by Taig** [comment]
Oh yeah, sorry, I forgot that there is no default Json `Parser`, because communicator doesn't depend on circe or any other JSON library. So personally I use circe for JSON with a `Parser` like this:
```scala
import io.circe.parser._
import cats.syntax.either._

implicit val parserJson: Parser[Json] = {
    Parser[String].mapResponse { ( response, content ) ⇒
        parse( content ).valueOr( throw _ )
    }
}
```

**Comment by fishmacs** [comment]
how about this valueOr?
error: value valueOr is not a member of Either[io.circe.ParsingFailure,io.circe.Json]

**Comment by Taig** [comment]
Did you add the imports?

**Comment by fishmacs** [comment]
Oh, cats...
ok now
